"""
Renders the files the wizard's Export page hands back to the developer:
`config.yaml`, and - when a branded build is wanted - `updater-brand.yaml`
plus a GitHub Actions workflow that calls `tools/build_branded.py`, and a
`README.md` walking through the remaining manual steps from `DEV_GUIDE.md`.

No PySide6 import, so this is covered directly by tests/test_setup_wizard.py.

Individual scalar/list values are rendered with `yaml.safe_dump` (never the
whole document at once) so the output is always syntactically valid YAML;
the surrounding structure and comments are a hand-written template mirroring
examples/config.yaml and examples/qsnippet-brand.yaml, because that's the
part a human is meant to read.
"""

from __future__ import annotations

import datetime as dt
import zipfile
from pathlib import Path

import yaml

BANNER = (
    "# Generated by `updater --setup` on {date}.\n"
    "# Review every value before committing this - the wizard fills in what\n"
    "# you told it, it does not know your app's actual release process.\n"
)


def y(value) -> str:
    """A YAML-safe scalar or flow list for one value."""
    dumped = yaml.safe_dump(value, default_flow_style=True, allow_unicode=True).strip()
    return dumped.split("\n", 1)[0]


def y_block(items, indent: str = "  ") -> str:
    """A block list for `key:{y_block(items)}`, or ` []` when empty."""
    items = [item for item in (items or []) if item not in (None, "")]
    if not items:
        return " []"
    return "\n" + "\n".join(f"{indent}- {y(item)}" for item in items)


def _today() -> str:
    return dt.datetime.now(dt.timezone.utc).strftime("%Y-%m-%d")


# --- config.yaml -------------------------------------------------------


def render_config_yaml(state) -> str:
    g = state.get

    return BANNER.format(date=_today()) + f"""
# QUpdateTool runtime configuration.
#
# Drop this next to the updater binary as "config.yaml" and it is picked up
# automatically, or point at it with --config. Flags override this file; a
# branded binary's locked fields override everything. See SECURITY.md.

app:
  name: {y(g("app.name"))}
  publisher: {y(g("app.publisher"))}
  current_version: {y(g("app.current_version"))}
  executable: {y(g("app.executable"))}
  install_dir: {y(g("app.install_dir"))}
  process_names:{y_block(g("app.process_names"))}
  support_url: {y(g("app.support_url"))}

source:
  provider: {y(g("source.provider"))}
  host: {y(g("source.host"))}
  repo: {y(g("source.repo"))}
  channel: {y(g("source.channel"))}
  tag_pattern: {y(g("source.tag_pattern"))}
  manifest_url: {y(g("source.manifest_url"))}
  download_url: {y(g("source.download_url"))}

  # NEVER put a token in a file that ships with the application. Name an
  # environment variable instead; the updater reads it at runtime.
  token_env: {y(g("source.token_env"))}

  timeout: {y(g("source.timeout"))}
  retries: {y(g("source.retries"))}
  verify_tls: {y(g("source.verify_tls"))}

assets:
  # Leave empty to let the updater pick using platform detection.
  preference:{y_block(g("assets.preference"))}
  pattern: {y(g("assets.pattern"))}
  exclude_pattern: {y(g("assets.exclude_pattern"))}
  match_arch: {y(g("assets.match_arch"))}

security:
  require_signature: {y(g("security.require_signature"))}
  require_checksum: {y(g("security.require_checksum"))}
  checksum_file: {y(g("security.checksum_file"))}
  signature_suffixes:{y_block(g("security.signature_suffixes"))}

  # A branded binary pins this at build time; set one of the two here only
  # for an unbranded/dev run.
  public_key_file: {y(g("security.public_key_file"))}
  allowed_fingerprints:{y_block(g("security.allowed_fingerprints"))}
  allow_gpg_fallback: {y(g("security.allow_gpg_fallback"))}

install:
  mode: {y(g("install.mode"))}
  elevate: {y(g("install.elevate"))}
  target_dir: {y(g("install.target_dir"))}
  download_dir: {y(g("install.download_dir"))}
  keep_download: {y(g("install.keep_download"))}

process:
  stop_parent: {y(g("process.stop_parent"))}
  stop_timeout: {y(g("process.stop_timeout"))}
  relaunch: {y(g("process.relaunch"))}
  wait_before_relaunch: {y(g("process.wait_before_relaunch"))}

notes:
  source: {y(g("notes.source"))}
  notices_dir: {y(g("notes.notices_dir"))}

ui:
  # The updater runs headless unless --gui is passed.
  gui: {y(g("ui.gui"))}
  confirm: {y(g("ui.confirm"))}
  window_title: {y(g("ui.window_title"))}
  accent_color: {y(g("ui.accent_color"))}
  auto_close_seconds: {y(g("ui.auto_close_seconds"))}

logging:
  level: {y(g("logging.level"))}
  # A file, or a directory to write "updater.log" into. Point this at the
  # application's own log directory. Use "none" to disable file logging.
  file: {y(g("logging.file"))}
"""


# --- updater-brand.yaml -------------------------------------------------


def render_brand_yaml(state) -> str:
    g = state.get
    w = state.wizard
    lock_fields = list(w.get("extra_lock_fields") or [])

    lock_section = ""
    if lock_fields:
        lock_section = (
            "\n# Additional fields to freeze beyond the automatic security-critical\n"
            "# lock (public key, provider, host, repo, manifest/download URL, TLS).\n"
            "lock:" + y_block(lock_fields)
        )

    return BANNER.format(date=_today()) + f"""
# Brand file for {g("app.name") or "this application"}.
#
# Compiled into updater.exe at build time by tools/build_branded.py. Keep
# this in YOUR app's repo, not in QUpdateTool2.0. Security-critical fields
# (public key, source.*) are locked automatically once any of them is set -
# see qupdatetool/brand.py.

app:
  name: {y(g("app.name"))}
  publisher: {y(g("app.publisher"))}
  support_url: {y(g("app.support_url"))}
  process_names:{y_block(g("app.process_names"))}

source:
  provider: {y(g("source.provider"))}
  host: {y(g("source.host"))}
  repo: {y(g("source.repo"))}
  channel: {y(g("source.channel"))}
  tag_pattern: {y(g("source.tag_pattern"))}

assets:
  preference:{y_block(g("assets.preference"))}
  exclude_pattern: {y(g("assets.exclude_pattern"))}

security:
  require_signature: {y(g("security.require_signature"))}
  require_checksum: {y(g("security.require_checksum"))}
  checksum_file: {y(g("security.checksum_file"))}
  signature_suffixes:{y_block(g("security.signature_suffixes"))}

  # The public key is injected at build time with --key (see the generated
  # CI workflow), so it is NOT written here.
  public_key_file: ""
  allowed_fingerprints:{y_block(g("security.allowed_fingerprints"))}

install:
  mode: {y(g("install.mode"))}
  elevate: {y(g("install.elevate"))}

process:
  stop_parent: {y(g("process.stop_parent"))}
  stop_timeout: {y(g("process.stop_timeout"))}
  relaunch: {y(g("process.relaunch"))}

notes:
  source: {y(g("notes.source"))}
  notices_dir: {y(g("notes.notices_dir"))}

ui:
  window_title: {y(g("ui.window_title"))}
  accent_color: {y(g("ui.accent_color"))}
  auto_close_seconds: {y(g("ui.auto_close_seconds"))}
{lock_section}
"""


# --- CI workflow ---------------------------------------------------------


def render_ci_yaml(state) -> str:
    w = state.wizard
    g = state.get
    targets = list(w.get("target_platforms") or ["windows-latest"])
    repo = w.get("qupdatetool_repo") or "queball1999/QUpdateTool2.0"
    ref = w.get("qupdatetool_ref") or "main"
    secret_name = w.get("key_secret_name") or "RELEASE_PUBLIC_KEY"
    icon_path = w.get("icon_path") or ""
    sign_command = w.get("sign_command") or ""

    icon_line = f'            --icon {icon_path} \\\n' if icon_path else ""
    gui_line = "            --gui \\\n" if w.get("build_gui") else ""
    sign_line = (
        f'            --sign-command "{sign_command}" \\\n' if sign_command else ""
    )

    return BANNER.format(date=_today()) + f"""
name: Build updater

on:
  push:
    tags:
      - "v*"
  workflow_dispatch: {{}}

jobs:
  build-updater:
    strategy:
      fail-fast: false
      matrix:
        os:{y_block(targets, indent="          ")}
    runs-on: ${{{{ matrix.os }}}}
    steps:
      - uses: actions/checkout@v7

      - uses: actions/checkout@v7
        with:
          repository: {repo}
          ref: {ref}
          path: qupdatetool

      - uses: actions/setup-python@v7
        with:
          python-version: "3.13"

      - run: pip install -r qupdatetool/requirements.txt -r qupdatetool/requirements-dev.txt

      - name: Write signing key
        shell: bash
        run: echo "${{{{ secrets.{secret_name} }}}}" > release-key.asc

      - name: Build branded updater
        shell: bash
        run: |
          python qupdatetool/tools/build_branded.py \\
            --brand updater-brand.yaml \\
{icon_line}{gui_line}            --key release-key.asc \\
{sign_line}            --clean

      - uses: actions/upload-artifact@v4
        with:
          name: updater-${{{{ matrix.os }}}}
          path: |
            dist/updater*

# {g("app.name") or "Your app"}'s own release pipeline should still pin the
# resulting sha256 and verify it before launching the updater - see
# DEV_GUIDE.md step 4 and SECURITY.md.
"""


# --- README ---------------------------------------------------------------


def render_readme(state) -> str:
    g = state.get
    w = state.wizard
    app_name = g("app.name") or "your application"
    branding = bool(w.get("branding_enabled"))

    lines = [
        f"# QUpdateTool integration bundle for {app_name}",
        "",
        f"Generated by `updater --setup` on {_today()}. Everything here is a",
        "starting point copied from your answers in the wizard - read it before",
        "committing it, the same way you would review a hand-written config.",
        "",
        "## What's in this bundle",
        "",
        "- `config.yaml` - runtime configuration. Drop it next to the updater",
        "  binary, or point at it with `--config`.",
    ]

    if branding:
        lines += [
            "- `updater-brand.yaml` - the brand file for a **branded** build.",
            "  Keep this in your app's own repository, not QUpdateTool's.",
            "- `.github/workflows/build-updater.yml` - builds the branded",
            "  `updater.exe` in CI and uploads it as a build artifact.",
        ]
        key_path = g("security.public_key_file", "")
        if key_path:
            lines.append(
                "- `release-key.asc` - the public signing key you supplied to the "
                "wizard, copied here for convenience."
            )

    lines += [
        "",
        "## Next steps",
        "",
        "1. Copy `config.yaml` next to your test build, or run it directly:",
        "   ```",
        "   python -m qupdatetool --config config.yaml --check-only --json",
        "   ```",
    ]

    if branding:
        secret_name = w.get("key_secret_name") or "RELEASE_PUBLIC_KEY"
        lines += [
            "2. Commit `updater-brand.yaml` and",
            "   `.github/workflows/build-updater.yml` to your app's repository.",
            f"3. Add a repository secret named `{secret_name}` containing your",
            "   **public** OpenPGP signing key (ASCII-armored). It's safe to",
            "   store as plain text - it's the public half of the key pair.",
            "4. Push a tag matching `v*` (or run the workflow manually) to build",
            "   the branded updater. Download the `updater-*` artifact from the",
            "   run and record its `.sha256` value in your app's build info -",
            "   see DEV_GUIDE.md step 4. **Never launch the updater without**",
            "   **checking that hash first.**",
            "5. Call the updater from your app:",
            "   ```",
            "   updater --check-only --json     # on startup, to show a badge",
            "   updater --gui                   # from Help > Check for Updates",
            "   ```",
        ]
    else:
        lines += [
            "2. This bundle has no brand file, so ship the updater unbranded",
            "   (`make build` in the QUpdateTool2.0 repo) and pass `--config`,",
            "   or generate a brand file too by re-running `updater --setup`",
            "   and turning on \"Build a branded binary in CI\".",
        ]

    lines += [
        "",
        "## Where to go for the full picture",
        "",
        "- DEV_GUIDE.md (QUpdateTool2.0 wiki) - the complete integration walkthrough",
        "- SECURITY.md (QUpdateTool2.0 repo) - the threat model behind every step above",
        "- README.md (QUpdateTool2.0 repo) - the full config.yaml / flag reference",
        "",
    ]

    return "\n".join(lines)


# --- export --------------------------------------------------------------


def build_export_bundle(state, zip_path) -> list:
    """Write the zip and return the list of member names it contains."""
    members = {"config.yaml": render_config_yaml(state)}

    if state.wizard.get("branding_enabled"):
        members["updater-brand.yaml"] = render_brand_yaml(state)
        members[".github/workflows/build-updater.yml"] = render_ci_yaml(state)

        key_path = state.get("security.public_key_file", "")
        if key_path:
            candidate = Path(key_path).expanduser()
            if candidate.is_file():
                members["release-key.asc"] = candidate.read_text(encoding="utf-8")

    members["README.md"] = render_readme(state)

    zip_path = Path(zip_path)
    zip_path.parent.mkdir(parents=True, exist_ok=True)

    with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED) as archive:
        for name, content in members.items():
            archive.writestr(name, content)

    return list(members)
